### PR TITLE
bugfix - nested directory upload

### PR DESCRIPTION
**Pull request by mcgalcode**

### CODE REVIEW

**Comment by maxhutch** [comment]
@mcgalcode can you update `requirements.txt` as well?

**Comment by mcgalcode** [comment]
@maxhutch bumping the pypif-sdk range seems to have solved the issue.

**Comment by maxhutch** [comment]
I still see an extra level of nesting.
upload_paths

**Comment by mcgalcode** [comment]
@maxhutch how are you doing that? I can't seem to reproduce

image

**Comment by maxhutch** [comment]
```
pif-ingestor/tests$ ~/anaconda3/bin/pif-ingestor -r -f dft dft -d {dataset id}
```

**Comment by mcgalcode** [comment]
OK I can reproduce with that, but the case in the ticket seems to be resolved.
```
pif-ingestor/tests$ ~/anaconda3/bin/pif-ingestor -f dft -d 40 dft/B.hR105/
```

**Pull request merged**
